### PR TITLE
Parsing changes

### PR DESCRIPTION
**Pull request by Senexis**
## Features
- Fixes cases where the mission names contains "(", like "The Index: Endurance (Low Risk)".
- Fixes cases where the location starts with "(Variant)" and add it to the front of the location.
- Fixes cases where the mission ends with "Extra", and add it to the end of the location.
- Adds ", Rotation A" to transients instead of just " A".
- Adds "Axi A1 Relic (Intact)" to relic locations instead of "Axi A1 Intact".
- Limit search results to improve performance.
  - Default is 100 results.
  - Option to set to 100, 250, 500, 1000, or all results.
  - Add a message how many more results are found.
  - Clem is not a number, apparently.

## Notes
Sorry about the messing up with the PR's earlier. Still getting to know the flow. 👍

### CODE REVIEW

**Comment by atomicptr** [comment]
I'd appreciate it if you'd (in the future) open the PR once you think you're done with what you wanted to do, because I now get an email for every push you do and it's also hard to see when I should start my review because it keeps changing :).

**Comment by Senexis** [comment]
Gotcha. Didn't know you guys got an email every single time. Sorry about that. Will do.

**Comment by atomicptr** [comment]
No problem ;)

**Comment by atomicptr** [comment]
Do you have a branch somewhere with these changes? 

image

Can't find them, wanted to test this :).

**Comment by atomicptr** [comment]
This made me learn a feature about Github that I didn't know... you can pull PRs with 

```shell
git pull origin pull/15/head
```

Very very useful :).

**Pull request merged**
