### PR TITLE
Implement all.slim.json feature.

### LINKED ISSUE #30: Generate a single drop item array at generate time.
### Warframe Drops Site Feature Request
---

**Summary (short):**
Generate a single array with all of the items.

---
**Detailed requirements of the feature**

_As a developer, it would hasten my workflow to not have to combine all drop items into a single array._
_As a user, it would hasten my pageload to never have to generate, only fetch, a json object to use._
_As a developer, it would ease my adoption of new data in the site if all of it was available from an always updated single-source, akin to All.json, but in a single array instead of in separate objects._

---
**Mockups:**

This should be as simple as adding a new file, let's call it `all.slim.json`, and exporting the output from the existing `formatData` function in `index.html` to this file when called with the existing `All.json` generated object.

---

**Additional context**
Instead of generating a new `_wfdata` object when there's a new hash, just always use a newly generated `all.slim.json` each time, which would be a single processed version of what is normally created when there's a new hash on the user's client.

### PR DESCRIPTION
**Pull request by Senexis**
### Warframe Drop Data Site Pull Request

---

**What I did:**
This moves data formatting to `generateData.js` to prevent client browsers having to format `all.json` themselves. This saves time on the client's end.

This might be an excellent time to do some refactoring, so if there's any ideas to do so, feel free to discuss (or edit if you're a collaborator). I tested this and it works. If this PR is merged, a generation should be run immediately. I didn't include `all.slim.json` as per requests in previous PRs I made.

Size difference:
**all.json**: 1769kb
**all.slim.json**: 1327kb

**Note:** This contains elements of PR #29. It doesn't depend on it but might cause conflicts if that PR is merged.

---
**Why I did it:**
As per suggestion of @TobiTenno in PR #29, it simply made sense to implement.

---
**Fixes issue (include link):**
Closes #30.

---
**Mockups, screenshots, evidence:**
This can be seen at https://senexis.github.io/warframe-drop-data.

---

**Was this an issue fix or a suggestion fulfillment?**
Suggestion fulfillment.

### CODE REVIEW

**Comment by Senexis** [comment]
Sorry about those, I messed up. 😢

**Comment by TobiTenno** [comment]
While we're in here, i do have some replaces that I think would be valuable to add in:

```js
newData.forEach((reward) => {
    reward.place = reward.place.replace('Derelict/', '') // eslint-disable-line no-param-reassign
      .replace('Assassinate (Assassination)', 'Assassinate')
      .replace('Defense (Defense)', 'Defense')
      .replace('Survival (Survival)', 'Survival')
      .replace('Teralyst (Special)', 'Teralyst (Capture)')
      .replace('Gantulyst (Special)', 'Gantulyst (Capture)')
      .replace('Hydrolyst (Special)', 'Hydrolyst (Capture)')
      .replace('The Law Of Retribution C', 'Law Of Retribution')
      .replace('The Jordas Verdict C', 'Jordas Verdict')
      .replace('The Law Of Retribution (Nightmare) C', 'Law Of Retribution (Nightmare)')
      .replace('Sanctuary/Elite Sanctuary Onslaught (Sanctuary Onslaught)', 'Elite Sanctuary Onslaught')
      .replace('Sanctuary/Sanctuary Onslaught (Sanctuary Onslaught)', 'Sanctuary Onslaught')
      .replace('/Lunaro Arena (Conclave)', '/Lunaro')
      .replace('/Lunaro Arena (Extra) (Conclave)', '/Lunaro')
      .replace('Variant Cephalon Capture (Conclave)', 'Variant Cephalon Capture')
      .replace('Variant Cephalon Capture (Extra) (Conclave)', 'Variant Cephalon Capture')
      .replace('Variant Team Annihilation (Extra) (Conclave)', 'Variant Team Annihilation')
      .replace('Variant Annihilation (Extra)', 'Variant Annihilation')
      .replace(' (Conclave)', '');
  });
```
These are to clean up misleading or redundant locations with types

**Comment by Senexis** [comment]
I'll see if this can't be accomplished without these replaces and instead clean on generation later. If that causes any issues, I'll include those replaces as a last resort.

**Comment by TobiTenno** [comment]
You'd have to replace sometime, lol. the problem is that none of them are exact duplicates, so regexing if one part is contained in another and not adding it won't work that well.

This way, they're already in objects, and it's not going to take much time to keep them clean once per rebuild.

**Comment by Senexis** [comment]
True, but stuff like `(extra)` and `(conclave)` can simply not be appended when generating those to avoid having to do any action at all, that's what I meant. 

Also, where did you find `The Law Of Retribution`, `The Jordas Verdict`, etc.? Are they in older builds? I can't seem to find them anywhere on DE's site.

**Comment by TobiTenno** [comment]
Oh, sorry, was getting ready to reply.

They're in older builds, a lot of them are built up over time, and it's easier to do it in a centralized location rather then having every consumer do it.

**Comment by Senexis** [comment]
On second thought, can conclave simply be removed completely like this? Seems to affect more entries than I thought. Not sure what the "gamemode" even is.

**Comment by TobiTenno** [comment]
Like entries that include conclave? It's possible, but I don't know that we'd want them removed.

`gamemode` is things like exterminate, conclave, defense... I think, or do we have a separate `missiontype`?

**Comment by Senexis** [comment]
The thing that's confusing me is that they act like regular mission nodes and yet have the game mode (or mission type, pretty much the same thing in this context) "conclave". I don't play enough PvP to know whether this is accurate to the game or not. The PvP stuff is weird in these drop tables.

**Comment by Senexis** [comment]
According to the wikia (http://warframe.wikia.com/wiki/Conclave), the "conclave" denotion is correct. Even for Lunaro. It makes sense to rename "Lunaro Arena" to "Lunaro", but I think leaving `(Conclave)` might be the better option.

**Comment by atomicptr** [comment]
Is this still WIP? Because on my end it looks good on my end, haven't tested it yet tho.

**Comment by TobiTenno** [comment]
@Senexis the `(Conclave)` demotion isn't wrong, but it's necessarily duplicated, as that mission type only appears as conclave and "conclave" isn't really a location.

**Comment by Senexis** [comment]
Agreed, however, to people like me who barely even know Lunaro and Cephalon Capture are a thing, knowing that it's Conclave, aka the PvP gamemode is definitely useful. Removing it for Lunaro would warrent it being removed on _all_ Conclave gamemodes (again, such as Lunaro and Cephalon Capture).

**Comment by TobiTenno** [comment]
Yes, that's how it was in the replacements I provided

**Comment by Senexis** [comment]
Your original replacements made it inconsistent though. Since Lunaro is just as much Conclave as Team Annihilation is, it would need to be removed everywhere.

**Comment by TobiTenno** [comment]
For now, I think you're right, and let's leave the "location" for it for now, and we can review in the future. the point is information. Most of the rest just get redundant or inaccurate, but if this helps clarify by having conclave marked, let's leave it in

**Comment by Senexis** [comment]
If there's nothing more to say, add, or change, can you merge this?

**Pull request merged**
