### PR TITLE
Implement key rewards.

### PR DESCRIPTION
**Pull request by Senexis**
### Warframe Drop Data Site Pull Request

---

**What I did:**
Implemented key rewards.

---
**Why I did it:**
To fix issue #28.

---
**Fixes issue (include link):**
Issue #28.

---
**Mockups, screenshots, evidence:**
Screenshot

---

**Was this an issue fix or a suggestion fulfillment?**
Fix.

### CODE REVIEW

**Comment by TobiTenno** [comment]
@atomicptr what would you think of, instead of doing all of this each time at runtime, we created something like an `all.slim.json` that was what we presently generate at runtime, but create it when the others are generated?

**Comment by Senexis** [comment]
Nothing is being done each time. All of this logic is only executed once.

Nevertheless, you could create the localstorage contents and store it in a seperate file, indeed. Wouldn't be too difficult either to do since json file is already pretty much in every browser's localstorage.

**Comment by TobiTenno** [comment]
`formatData` is definitely called when starting up the page [here](https://github.com/Senexis/warframe-drop-data/blob/39f1b5bfb56710b5795792dec88fed92099dd194/index.html#L201)

**Comment by Senexis** [comment]
Yup! `if (hash !== oldData.hash)`. :)

**Comment by TobiTenno** [comment]
"once" would imply once globally. "Once per user/browser" is more accurate, and considering it should be the same for everyone, there's no reason not to make it globally stored and fetched. This would also make it easier for, say, an api that tries to consistently consume this?

**Comment by Senexis** [comment]
It would be. I would personally refrain from opening this as an official "API" and just keep it as a site asset. You want to optimize such a file solely for the purpose of the site instead of catering to other possible implementations.

**Comment by Senexis** [comment]
Turns out this is _extremely_ trivial to accomplish. Simply rip out the entire `formatData` function and call it with `all.json` when it is generated, and change the URL within `index.html` to reflect that. Easy as pie. +1 for that idea.

**Comment by TobiTenno** [comment]
I didn't think it was at all difficult to accomplish at generation time, that's why I asked.... I'll put up an issue for it.

**Comment by TobiTenno** [comment]
Personally, I prefer [`Array.forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) going forward, but I understand hesitation since it _only_ has support back to IE 9

**Comment by TobiTenno** [comment]
@Senexis i'll probably merge this first, so you might need to rebase your changes for #31

**Pull request merged**
