### PR TITLE
Stalker theme support

### PR DESCRIPTION
**Pull request by TobiTenno**
ummmm, something went wrong

### CODE REVIEW

**Comment by atomicptr** [comment]
image

:thinking: why is this already on live?

**Comment by TobiTenno** [comment]
clicking too fast

**Comment by atomicptr** [comment]
image

Looks fine beyond this, can you resolve that just merge it yourself :D?

**Comment by TobiTenno** [comment]
Yeah, we can actually close this one, since it got popped into live. i'll keep an eye out for issues.

**Pull request closed without merging**
